Watching for file changes with StatReloader
Superuser creation skipped due to not running in a TTY. You can run `manage.py createsuperuser` in your project to create one manually.
[14/Mar/2021 11:09:57] "POST /api-auth/login/ HTTP/1.1" 302 0
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 399, in to_representation
    url = self.get_url(value, self.view_name, request, format)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 337, in get_url
    return self.reverse(view_name, kwargs=kwargs, request=request, format=format)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/reverse.py", line 47, in reverse
    url = _reverse(viewname, args, kwargs, request, format, **extra)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/reverse.py", line 60, in _reverse
    url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user-detail' not found. 'user-detail' is not a valid view function or pattern name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 696, in get_context
    'post_form': self.get_rendered_html_form(data, view, 'POST', request),
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 511, in get_rendered_html_form
    return self.render_form_for_serializer(serializer)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 521, in render_form_for_serializer
    {'style': {'template_pack': 'rest_framework/horizontal'}}
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 372, in render
    return template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/templatetags/rest_framework.py", line 87, in render_field
    return renderer.render_field(field, style)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 351, in render_field
    return template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 163, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 220, in iter_options
    self.get_choices(cutoff=self.html_cutoff),
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 207, in get_choices
    for item in queryset
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 207, in <listcomp>
    for item in queryset
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 414, in to_representation
    raise ImproperlyConfigured(msg % self.view_name)
django.core.exceptions.ImproperlyConfigured: Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
[14/Mar/2021 11:09:57] "GET /users/ HTTP/1.1" 500 258434
[14/Mar/2021 11:10:03] "GET / HTTP/1.1" 200 6083
[14/Mar/2021 11:10:03] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:10:03] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:10:03] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:10:03] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:10:03] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:10:03] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:10:03] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:10:03] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:10:03] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:10:03] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:10:03] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:09:17
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[14/Mar/2021 11:10:11] "GET /users/ HTTP/1.1" 200 9374
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: cosmetic_analyze_profile.date_joined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 792, in save_base
    force_update, using, update_fields,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: cosmetic_analyze_profile.date_joined
[14/Mar/2021 11:10:24] "POST /users/ HTTP/1.1" 500 195662
[14/Mar/2021 11:10:45] "GET /admin/ HTTP/1.1" 200 3322
[14/Mar/2021 11:10:45] "GET /static/admin/css/base.css HTTP/1.1" 200 16307
[14/Mar/2021 11:10:45] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2138
[14/Mar/2021 11:10:45] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 380
[14/Mar/2021 11:10:45] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
[14/Mar/2021 11:10:45] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18344
[14/Mar/2021 11:10:45] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[14/Mar/2021 11:10:45] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[14/Mar/2021 11:10:45] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[14/Mar/2021 11:10:45] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[14/Mar/2021 11:10:45] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[14/Mar/2021 11:10:45] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[14/Mar/2021 11:10:46] "GET /admin/auth/group/ HTTP/1.1" 200 4729
[14/Mar/2021 11:10:47] "GET /static/admin/css/base.css HTTP/1.1" 200 16307
[14/Mar/2021 11:10:47] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2138
[14/Mar/2021 11:10:47] "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
[14/Mar/2021 11:10:47] "GET /admin/jsi18n/ HTTP/1.1" 200 8314
[14/Mar/2021 11:10:47] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 287630
[14/Mar/2021 11:10:47] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 1360
[14/Mar/2021 11:10:47] "GET /static/admin/css/changelists.css HTTP/1.1" 200 6302
[14/Mar/2021 11:10:47] "GET /static/admin/js/core.js HTTP/1.1" 200 5418
[14/Mar/2021 11:10:47] "GET /static/admin/js/actions.js HTTP/1.1" 200 6783
[14/Mar/2021 11:10:47] "GET /static/admin/js/urlify.js HTTP/1.1" 200 8632
[14/Mar/2021 11:10:47] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 6078
[14/Mar/2021 11:10:47] "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
[14/Mar/2021 11:10:47] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[14/Mar/2021 11:10:47] "GET /static/admin/img/search.svg HTTP/1.1" 200 458
[14/Mar/2021 11:10:47] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
[14/Mar/2021 11:10:48] "GET /admin/auth/user/ HTTP/1.1" 200 8006
[14/Mar/2021 11:10:48] "GET /admin/jsi18n/ HTTP/1.1" 200 8314
[14/Mar/2021 11:10:48] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
[14/Mar/2021 11:10:48] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[14/Mar/2021 11:11:08] "GET /users/ HTTP/1.1" 200 9374
[14/Mar/2021 11:11:08] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:11:08] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:11:08] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:11:08] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:11:08] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:11:08] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:11:08] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:11:08] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:11:08] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:11:08] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:11:08] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
/tuto/4주차/cosmetic_analyze/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:10:10
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:15:12
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[14/Mar/2021 11:15:34] "GET / HTTP/1.1" 200 6083
[14/Mar/2021 11:15:34] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:15:34] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:15:34] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:15:34] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:15:34] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:15:34] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:15:34] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:15:34] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:15:34] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:15:34] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:15:34] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[14/Mar/2021 11:15:35] "GET /users/ HTTP/1.1" 200 9374
Bad Request: /users/
[14/Mar/2021 11:15:50] "POST /users/ HTTP/1.1" 400 9824
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: cosmetic_analyze_profile.date_joined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 792, in save_base
    force_update, using, update_fields,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: cosmetic_analyze_profile.date_joined
[14/Mar/2021 11:15:56] "POST /users/ HTTP/1.1" 500 195536
[14/Mar/2021 11:16:07] "GET /admin/auth/user/ HTTP/1.1" 200 8006
[14/Mar/2021 11:16:07] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[14/Mar/2021 11:16:07] "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
[14/Mar/2021 11:16:07] "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
[14/Mar/2021 11:16:07] "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/js/core.js HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /admin/jsi18n/ HTTP/1.1" 200 8314
[14/Mar/2021 11:16:08] "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/img/search.svg HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/img/icon-yes.svg HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 304 0
[14/Mar/2021 11:16:08] "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 304 0
[14/Mar/2021 11:16:11] "GET /admin/auth/user/add/ HTTP/1.1" 200 7040
[14/Mar/2021 11:16:11] "GET /static/admin/css/forms.css HTTP/1.1" 200 8423
[14/Mar/2021 11:16:11] "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 492
[14/Mar/2021 11:16:11] "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
[14/Mar/2021 11:16:11] "GET /admin/jsi18n/ HTTP/1.1" 200 8314
[14/Mar/2021 11:16:11] "GET /static/admin/css/widgets.css HTTP/1.1" 200 10592
[14/Mar/2021 11:16:20] "POST /admin/auth/user/add/ HTTP/1.1" 200 7231
[14/Mar/2021 11:16:20] "GET /admin/jsi18n/ HTTP/1.1" 200 8314
[14/Mar/2021 11:16:28] "POST /admin/auth/user/add/ HTTP/1.1" 200 7319
[14/Mar/2021 11:16:28] "GET /admin/jsi18n/ HTTP/1.1" 200 8314
[14/Mar/2021 11:16:38] "POST /admin/auth/user/add/ HTTP/1.1" 302 0
[14/Mar/2021 11:16:38] "GET /admin/auth/user/2/change/ HTTP/1.1" 200 17092
[14/Mar/2021 11:16:38] "GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4257
[14/Mar/2021 11:16:38] "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19750
[14/Mar/2021 11:16:38] "GET /static/admin/js/calendar.js HTTP/1.1" 200 7788
[14/Mar/2021 11:16:38] "GET /admin/jsi18n/ HTTP/1.1" 200 8314
[14/Mar/2021 11:16:38] "GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 12350
[14/Mar/2021 11:16:38] "GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
[14/Mar/2021 11:16:38] "GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
[14/Mar/2021 11:16:38] "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[14/Mar/2021 11:16:38] "GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
[14/Mar/2021 11:16:38] "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[14/Mar/2021 11:16:40] "GET /admin/auth/user/ HTTP/1.1" 200 8394
[14/Mar/2021 11:16:40] "GET /admin/jsi18n/ HTTP/1.1" 200 8314
[14/Mar/2021 11:16:40] "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
[14/Mar/2021 11:16:45] "GET /users/ HTTP/1.1" 200 9374
[14/Mar/2021 11:16:48] "GET /users/ HTTP/1.1" 200 9374
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:15:28
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[14/Mar/2021 11:17:18] "GET / HTTP/1.1" 200 6083
[14/Mar/2021 11:17:18] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:17:18] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:17:18] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:17:18] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:17:18] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:18] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:18] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:18] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:18] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:18] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:18] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 250, in data
    self._data = self.get_initial()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 398, in get_initial
    for field in self.fields.values()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 349, in fields
    for key, value in self.get_fields().items():
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1035, in get_fields
    field_names, declared_fields, extra_kwargs
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1390, in get_uniqueness_extra_kwargs
    field_names, declared_fields, extra_kwargs
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1472, in _get_model_fields
    if '.' in source or source == '*':
TypeError: argument of type 'DeferredAttribute' is not iterable
[14/Mar/2021 11:17:19] "GET /users/ HTTP/1.1" 500 119221
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:17:17
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[14/Mar/2021 11:17:46] "GET /users/ HTTP/1.1" 200 9374
[14/Mar/2021 11:17:46] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:17:46] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:17:46] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:46] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:17:46] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:17:46] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:46] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:46] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:46] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:46] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:17:46] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:17:45
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[14/Mar/2021 11:18:41] "GET /users/ HTTP/1.1" 200 9374
[14/Mar/2021 11:18:42] "GET / HTTP/1.1" 200 6083
[14/Mar/2021 11:18:43] "GET /users/ HTTP/1.1" 200 9374
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:18:39
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:18:58
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tuto/4주차/config/urls.py", line 4, in <module>
    from cosmetic_analyze import views
  File "/tuto/4주차/cosmetic_analyze/views.py", line 5, in <module>
    from cosmetic_analyze.serializers import ProfileSerializer, CosmeticSerializer, CategorySerializer, IngredientSerializer, CommentSerializer
  File "/tuto/4주차/cosmetic_analyze/serializers.py", line 12
    def create()
               ^
SyntaxError: invalid syntax

/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
[14/Mar/2021 11:29:27] "GET / HTTP/1.1" 200 6083
[14/Mar/2021 11:29:27] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:29:27] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:27] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:27] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:29:27] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:29:27] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:27] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:27] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:27] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:29:27] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:27] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[14/Mar/2021 11:29:28] "GET /users/ HTTP/1.1" 200 9374
[14/Mar/2021 11:29:36] "GET /users/ HTTP/1.1" 200 9374
[14/Mar/2021 11:29:36] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:29:36] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:29:36] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:36] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:36] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:29:36] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:29:36] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:36] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:36] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:36] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:29:36] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[14/Mar/2021 11:29:53] "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1746
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:29:26
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[14/Mar/2021 11:30:22] "GET /users/ HTTP/1.1" 200 9374
[14/Mar/2021 11:30:22] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:30:22] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:30:22] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:30:22] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:30:22] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:30:22] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:30:22] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:30:22] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:30:22] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:30:22] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:30:22] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[14/Mar/2021 11:30:23] "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1746
[14/Mar/2021 11:30:24] "GET / HTTP/1.1" 200 6083
[14/Mar/2021 11:30:24] "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1746
[14/Mar/2021 11:30:25] "GET /users/ HTTP/1.1" 200 9374
[14/Mar/2021 11:30:25] "GET /static/rest_framework/css/bootstrap.min.css.map HTTP/1.1" 404 1746
/tuto/4주차/cosmetic_analyze/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:30:20
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
[14/Mar/2021 11:34:23] "GET /users/ HTTP/1.1" 200 9374
[14/Mar/2021 11:34:23] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:34:23] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:34:23] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:34:23] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:34:23] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:34:23] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:34:23] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:34:23] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:34:23] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:34:23] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:34:23] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: cosmetic_analyze_profile.date_joined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 792, in save_base
    force_update, using, update_fields,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: cosmetic_analyze_profile.date_joined
[14/Mar/2021 11:34:39] "POST /users/ HTTP/1.1" 500 195659
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:34:13
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/tuto/4주차/cosmetic_analyze/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:34:54
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tuto/4주차/config/urls.py", line 4, in <module>
    from cosmetic_analyze import views
  File "/tuto/4주차/cosmetic_analyze/views.py", line 8, in <module>
    class ProfileViewSet(viewsets.ModelViewSet):
  File "/tuto/4주차/cosmetic_analyze/views.py", line 9, in ProfileViewSet
    queryset = Profile.objects.all().order_by('-joined_at')
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 1134, in order_by
    obj.query.add_ordering(*field_names)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1919, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'joined_at' into field. Choices are: email, id, name, skin_type, user, user_id

/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tuto/4주차/config/urls.py", line 4, in <module>
    from cosmetic_analyze import views
  File "/tuto/4주차/cosmetic_analyze/views.py", line 8, in <module>
    class ProfileViewSet(viewsets.ModelViewSet):
  File "/tuto/4주차/cosmetic_analyze/views.py", line 9, in ProfileViewSet
    queryset = Profile.objects.all().order_by('-joined_at')
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 1134, in order_by
    obj.query.add_ordering(*field_names)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1919, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'joined_at' into field. Choices are: email, id, name, skin_type, user, user_id

/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tuto/4주차/config/urls.py", line 4, in <module>
    from cosmetic_analyze import views
  File "/tuto/4주차/cosmetic_analyze/views.py", line 8, in <module>
    class ProfileViewSet(viewsets.ModelViewSet):
  File "/tuto/4주차/cosmetic_analyze/views.py", line 9, in ProfileViewSet
    queryset = Profile.objects.all().order_by('-joined_at')
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 1134, in order_by
    obj.query.add_ordering(*field_names)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1919, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'joined_at' into field. Choices are: email, id, name, skin_type, user, user_id

/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tuto/4주차/config/urls.py", line 4, in <module>
    from cosmetic_analyze import views
  File "/tuto/4주차/cosmetic_analyze/views.py", line 8, in <module>
    class ProfileViewSet(viewsets.ModelViewSet):
  File "/tuto/4주차/cosmetic_analyze/views.py", line 9, in ProfileViewSet
    queryset = Profile.objects.all().order_by('-joined_at')
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 1134, in order_by
    obj.query.add_ordering(*field_names)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1919, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'joined_at' into field. Choices are: email, id, name, skin_type, user, user_id

/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/management/base.py", line 396, in check
    databases=databases,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 408, in check
    for pattern in self.url_patterns:
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/tuto/4주차/config/urls.py", line 4, in <module>
    from cosmetic_analyze import views
  File "/tuto/4주차/cosmetic_analyze/views.py", line 8, in <module>
    class ProfileViewSet(viewsets.ModelViewSet):
  File "/tuto/4주차/cosmetic_analyze/views.py", line 9, in ProfileViewSet
    queryset = Profile.objects.all().order_by('-joined_at')
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 1134, in order_by
    obj.query.add_ordering(*field_names)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1919, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1482, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'joined_at' into field. Choices are: email, id, name, skin_type, user, user_id

/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Watching for file changes with StatReloader
[14/Mar/2021 11:39:36] "GET / HTTP/1.1" 200 6083
[14/Mar/2021 11:39:36] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:39:36] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:39:36] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:39:36] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:39:36] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:39:36] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:39:36] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:39:36] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:39:36] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:39:36] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:39:36] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 250, in data
    self._data = self.get_initial()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 398, in get_initial
    for field in self.fields.values()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 349, in fields
    for key, value in self.get_fields().items():
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1029, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1130, in get_field_names
    serializer_class=self.__class__.__name__
AssertionError: The field 'user' was declared on serializer ProfileSerializer, but has not been included in the 'fields' option.
[14/Mar/2021 11:39:38] "GET /users/ HTTP/1.1" 500 115088
/tuto/4주차/cosmetic_analyze/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:39:33
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 250, in data
    self._data = self.get_initial()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 398, in get_initial
    for field in self.fields.values()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 349, in fields
    for key, value in self.get_fields().items():
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1029, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1130, in get_field_names
    serializer_class=self.__class__.__name__
AssertionError: The field 'user' was declared on serializer ProfileSerializer, but has not been included in the 'fields' option.
[14/Mar/2021 11:44:09] "GET /users/ HTTP/1.1" 500 115582
[14/Mar/2021 11:44:11] "GET / HTTP/1.1" 200 6083
[14/Mar/2021 11:44:11] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:44:11] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:44:11] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:44:11] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:44:11] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:44:11] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:44:11] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:44:11] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:44:11] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:44:11] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:44:11] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 250, in data
    self._data = self.get_initial()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 398, in get_initial
    for field in self.fields.values()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 349, in fields
    for key, value in self.get_fields().items():
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1029, in get_fields
    field_names = self.get_field_names(declared_fields, info)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1130, in get_field_names
    serializer_class=self.__class__.__name__
AssertionError: The field 'user' was declared on serializer ProfileSerializer, but has not been included in the 'fields' option.
[14/Mar/2021 11:44:12] "GET /users/ HTTP/1.1" 500 115445
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:44:06
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 655, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 250, in data
    self._data = self.get_initial()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 398, in get_initial
    for field in self.fields.values()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 349, in fields
    for key, value in self.get_fields().items():
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1054, in get_fields
    source, info, model, depth
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1199, in build_field
    return self.build_unknown_field(field_name, model_class)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 1319, in build_unknown_field
    (field_name, model_class.__name__)
django.core.exceptions.ImproperlyConfigured: Field name `__all__` is not valid for model `Profile`.
[14/Mar/2021 11:44:33] "GET /users/ HTTP/1.1" 500 118708
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:44:33
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 399, in to_representation
    url = self.get_url(value, self.view_name, request, format)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 337, in get_url
    return self.reverse(view_name, kwargs=kwargs, request=request, format=format)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/reverse.py", line 47, in reverse
    url = _reverse(viewname, args, kwargs, request, format, **extra)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/reverse.py", line 60, in _reverse
    url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user-detail' not found. 'user-detail' is not a valid view function or pattern name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 696, in get_context
    'post_form': self.get_rendered_html_form(data, view, 'POST', request),
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 511, in get_rendered_html_form
    return self.render_form_for_serializer(serializer)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 521, in render_form_for_serializer
    {'style': {'template_pack': 'rest_framework/horizontal'}}
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 372, in render
    return template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/templatetags/rest_framework.py", line 87, in render_field
    return renderer.render_field(field, style)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 351, in render_field
    return template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 163, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 220, in iter_options
    self.get_choices(cutoff=self.html_cutoff),
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 207, in get_choices
    for item in queryset
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 207, in <listcomp>
    for item in queryset
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 414, in to_representation
    raise ImproperlyConfigured(msg % self.view_name)
django.core.exceptions.ImproperlyConfigured: Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
[14/Mar/2021 11:44:54] "GET /users/ HTTP/1.1" 500 258143
[14/Mar/2021 11:44:57] "GET / HTTP/1.1" 200 6083
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 399, in to_representation
    url = self.get_url(value, self.view_name, request, format)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 337, in get_url
    return self.reverse(view_name, kwargs=kwargs, request=request, format=format)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/reverse.py", line 47, in reverse
    url = _reverse(viewname, args, kwargs, request, format, **extra)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/reverse.py", line 60, in _reverse
    url = django_reverse(viewname, args=args, kwargs=kwargs, **extra)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/base.py", line 87, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/urls/resolvers.py", line 685, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'user-detail' not found. 'user-detail' is not a valid view function or pattern name.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 696, in get_context
    'post_form': self.get_rendered_html_form(data, view, 'POST', request),
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 511, in get_rendered_html_form
    return self.render_form_for_serializer(serializer)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 521, in render_form_for_serializer
    {'style': {'template_pack': 'rest_framework/horizontal'}}
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 372, in render
    return template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 211, in render
    nodelist.append(node.render_annotated(context))
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 312, in render
    return nodelist.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/templatetags/rest_framework.py", line 87, in render_field
    return renderer.render_field(field, style)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/renderers.py", line 351, in render_field
    return template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/defaulttags.py", line 163, in render
    values = self.sequence.resolve(context, ignore_failures=True)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 671, in resolve
    obj = self.var.resolve(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 796, in resolve
    value = self._resolve_lookup(context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/template/base.py", line 858, in _resolve_lookup
    current = current()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 220, in iter_options
    self.get_choices(cutoff=self.html_cutoff),
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 207, in get_choices
    for item in queryset
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 207, in <listcomp>
    for item in queryset
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/relations.py", line 414, in to_representation
    raise ImproperlyConfigured(msg % self.view_name)
django.core.exceptions.ImproperlyConfigured: Could not resolve URL for hyperlinked relationship using view name "user-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
[14/Mar/2021 11:44:58] "GET /users/ HTTP/1.1" 500 258150
/tuto/4주차/cosmetic_analyze/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:44:52
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/tuto/4주차/cosmetic_analyze/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:45:44
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
/tuto/4주차/cosmetic_analyze/serializers.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:45:58
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
[14/Mar/2021 11:46:44] "GET /users/ HTTP/1.1" 200 9386
[14/Mar/2021 11:46:44] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[14/Mar/2021 11:46:44] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[14/Mar/2021 11:46:44] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[14/Mar/2021 11:46:44] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[14/Mar/2021 11:46:44] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:46:44] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[14/Mar/2021 11:46:44] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[14/Mar/2021 11:46:44] "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 304 0
[14/Mar/2021 11:46:44] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[14/Mar/2021 11:46:44] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[14/Mar/2021 11:46:44] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Not Found: /u
[14/Mar/2021 11:46:46] "GET /u HTTP/1.1" 404 6977
[14/Mar/2021 11:46:47] "GET / HTTP/1.1" 200 6083
[14/Mar/2021 11:46:48] "GET /users/ HTTP/1.1" 200 9386
Internal Server Error: /users/
Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: cosmetic_analyze_profile.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/mixins.py", line 19, in create
    self.perform_create(serializer)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/mixins.py", line 24, in perform_create
    serializer.save()
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/tuto/4주차/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 939, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 447, in create
    obj.save(force_insert=True, using=self.db)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 754, in save
    force_update=force_update, update_fields=update_fields)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 792, in save_base
    force_update, using, update_fields,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 895, in _save_table
    results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/base.py", line 935, in _do_insert
    using=using, raw=raw,
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/query.py", line 1254, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1397, in execute_sql
    cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/tuto/4주차/env/lib/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: cosmetic_analyze_profile.username
[14/Mar/2021 11:46:55] "POST /users/ HTTP/1.1" 500 195578
/tuto/4주차/cosmetic_analyze/models.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
March 14, 2021 - 11:46:42
Django version 3.1.7, using settings 'config.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
